# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
#baseurl: "" # does not include hostname
#show_dir_listing: false

host: 0.0.0.0
port:  4000
siteurl: https://spactimes.com
title: "Outvanity Blog"
description: "侃侃理想、谈谈人生、敲敲代码。"
url: https://spactimes.com # 域名
# signoff: "outvanity" # Your name
# facebook_appid: #outvanity
# google_analytics: UA-101222464-1
share: true 
detach: false
# 分页

plugins: [jekyll-paginate]

paginate: 5
paginate_path: "outvanity:num"

sass:
  style: compressed
exclude:
- ".gitignore"
- CNAME

links:
  - name:         首页
    url:          /
    external:     false
  - name:         代码
    url:          /code
    external:     false 
  - name:         书籍
    url:          /book
    external:     false
  - name:         杂言
    url:          /miscellaneous
    external:     false
  - name:         历史
    url:          /history
    external:     false
  - name:         标签
    url:          /tags
    external:     false
  - name:         关于
    url:          /about
    external:     false
# ------------ CONFIGURABLE END ------------

#permalink:        /:categories/:title.html
permalink: /:year/:month/:day/:title.html
defaults:
  - values:
      layout: "blog"




markdown: kramdown


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
 - Gemfile
 - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
