# ----------- CONFIGURABLE START -----------
title:            "EyebrowHairs"
description:      "Musings and memoirs"
url:              https://eyebrowhairs.github.io 
signoff:          "EyebrowHairs" # Your name
facebook_appid:   #eyebrowhairs
google_analytics: 
share:            true 

paginate: 15
paginate_path: "eyebrowhairs:num"
gems: [jekyll-paginate]
links:
  - name:         Home
    url:          /
    external:     false
  - name:         Blog
    url:          /blog
    external:     false
  - name:         Portfolio
    url:          /portfolio
    external:     false
  - name:         Archives
    url:          /archives
    external:     false
  - name:         Tags
    url:          /tags
    external:     false
  - name:         About
    url:          /about
    external:     false
# ------------ CONFIGURABLE END ------------

#permalink:        /:categories/:title.html
permalink: /:year/:month/:day/:title.html
defaults:
  - values:
      layout: "default"
